version: 0.2

env:
  variables:
    APP: PSW
    REPO: https://github.com/hms-dbmi/pic-sure-wildfly-docker
    IMAGE: "pic-sure-wildfly"
    TAG: LATEST
  secrets-manager:
    DOCKER_HUB_USERNAME: "/hms/dbmi/ppm/neer/pic-sure/pipelines:username"
    DOCKER_HUB_PASSWORD: "/hms/dbmi/ppm/neer/pic-sure/pipelines:password"

phases:
  install:
    commands:
      - echo Installing codebuild-extras...
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/fd64ace08a309109058c461e6997807e7473fc61/install >> extras.sh
      - . ./extras.sh
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - git clone $REPO /tmp/source
      - docker build -t $IMAGE:$TAG /tmp/source
      - docker tag $IMAGE:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$TAG
      - docker tag $IMAGE:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$CODEBUILD_GIT_COMMIT
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:$CODEBUILD_GIT_COMMIT
