version: 0.2

env:
  variables:
    APP: PSW
    REPO: https://github.com/hms-dbmi/pic-sure-wildfly-docker
    IMAGE: "pic-sure-wildfly"
    TAG: LATEST
  secrets-manager:
    DOCKER_HUB_USERNAME: "/hms/dbmi/ppm/neer/pic-sure/pipelines:username"
    DOCKER_HUB_PASSWORD: "/hms/dbmi/ppm/neer/pic-sure/pipelines:password"

phases:
  install:
    commands:
      - yum install -y jq git curl
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - export COMMIT=`cat build-spec.json | jq -r ".application[] | select(.project_job_git_key == \"${APP}\") | .git_hash"`
      - export PSA_COMMIT=`cat build-spec.json | jq -r ".application[] | select(.project_job_git_key == \"PSA\") | .git_hash"`
      - export PSAMA_COMMIT=`cat build-spec.json | jq -r ".application[] | select(.project_job_git_key == \"PSAMA\") | .git_hash"`
      - echo Checking out $REPO @ $COMMIT...
      - git clone -n $REPO /tmp/source
      - cd /tmp/source
      - git checkout $COMMIT
      - echo Patching Dockerfile to import from ${IMAGE%/*}/pic-sure-api:$PSA_COMMIT...
      - sed -i "s|^FROM .* AS PSA$|FROM ${IMAGE%/*}/pic-sure-api:$PSA_COMMIT AS PSA|gI" /tmp/source/ui/Dockerfile
      - echo Patching Dockerfile to import from ${IMAGE%/*}/pic-sure-auth-microapp:$PSAMA_COMMIT...
      - sed -i "s|^FROM .* AS PSAMA$|FROM ${IMAGE%/*}/pic-sure-auth-microapp:$PSAMA_COMMIT AS PSAMA|gI" /tmp/source/ui/Dockerfile
      - echo Building $IMAGE image...
      - docker build --build-arg PIC_SURE_PASSTHRU_RESOURCE_VERSION=LATEST -t $IMAGE:$TAG /tmp/source
      - docker tag $IMAGE:$TAG $IMAGE:$COMMIT
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing $IMAGE image...
      - docker push $IMAGE:$TAG
      - docker push $IMAGE:$COMMIT
