version: 0.2

env:
  variables:
    APP: PSA
    REPO: https://github.com/hms-dbmi/pic-sure.git
    IMAGE: "pic-sure-api"
    TAG: LATEST
  secrets-manager:
    DOCKER_HUB_USERNAME: "/hms/dbmi/ppm/neer/pic-sure/pipelines:username"
    DOCKER_HUB_PASSWORD: "/hms/dbmi/ppm/neer/pic-sure/pipelines:password"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum install -y jq git curl
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - export COMMIT=`cat build-spec.json| jq -r ".application[] | select(.project_job_git_key == \"${APP}\") | .git_hash"`
      - echo Checking out $REPO @ $COMMIT...
      - git clone -n $REPO /tmp/source
      - cd /tmp/source && git checkout $COMMIT
      - echo Building ${IMAGE} source...
      - mvn -Dmaven.repo.local=$CODEBUILD_SHARED_CACHE --no-transfer-progress --batch-mode clean install -DskipTests -Dwildfly.skip=true
      - echo Building ${IMAGE} image...
      - docker build -t $IMAGE:$TAG /tmp/source/pic-sure-api-war
      - docker tag $IMAGE:$TAG $IMAGE:$COMMIT
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing ${IMAGE} image...
      - docker push $IMAGE:$TAG
      - docker push $IMAGE:$COMMIT
      - echo Renaming artifact /tmp/source/pic-sure-api-war/target/pic-sure-api-war.war to /tmp/source/pic-sure-api-war/target/pic-sure-api-2.war
      - mv /tmp/source/pic-sure-api-war/target/pic-sure-api-war.war /tmp/source/pic-sure-api-war/target/pic-sure-api-2.war

artifacts:
  files:
    - /tmp/source/pic-sure-api-war/target/pic-sure-api-2.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
